#!/bin/sh
export LD_LIBRARY_PATH=/lib:/root/lib
export PATH=/bin:/sbin:/usr/local/bin:/usr/local/sbin:/root/bin:/root/sbin:/data

### tslib env
source /etc/ts_env.sh

# auto mount sdcard
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

ulimit -c unlimited
cd /root/usr

. /root/usr/net_path.sh

cp face_model/rkdsp.bin /lib/firmware/ 
insmod rs.ko

# 开机加载wifi模块
./wifi/wifi_init.sh

# 判断开机是否启动wifi
wifi_enable=`busybox awk 'BEGIN {FS="="}/\[wireless\]/{a=1} a==1&&$1~/^enable/{gsub(/\"/,"",$2);gsub(/\;.*/, "", $2);gsub(/^[[:blank:]]*/,"",$2);print $2}' $inifile`
if [ "$wifi_enable" = "1" ]; then
	./wifi/wifi_start.sh
	# start telnet   
	busybox telnetd
fi
#./monitor.sh &


