#!/bin/sh

mkdir -p /temp
ifconfig wlan0:1 172.16.1.2 netmask 255.255.0.0
if [ ! -e "/temp/cat_eye" ] ;then
	echo "mounting ..."
	mount -t nfs -o nolock 172.16.1.102:/home/xubin/work/arm_share/cat_eye /temp
fi

if [ $# == 1  ]; then
	if [ $1 == 1 ]; then
		echo "cp /temp/cat_eye ."
		cp /temp/cat_eye .
		./cat_eye
	elif [ $1 == 2 ]; then
		echo "cp /temp/cammer_video /data"
		cp /temp/cammer_video /data/
		/data/cammer_video &
	fi
fi


